# Inisialisasi awal

In [163]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/hr-analytics/HR_comma_sep.csv


# Import dataset

In [164]:
hr_df = pd.read_csv('../input/hr-analytics/HR_comma_sep.csv')
hr_df.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years Department  \
0                   3              0     1                      0      sales   
1                   6              0     1                      0      sales   
2                   4              0     1                      0      sales   
3                   5              0     1                      0      sales   
4                   3              0     1                      0      sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

# Membersihkan NaN value jika ada

In [165]:
hr_df.shape

(14999, 10)

In [166]:
hr_df = hr_df.dropna()
hr_df.shape

(14999, 10)

# Mempersiapkan dataset untuk machine learning

In [170]:
from sklearn.model_selection import train_test_split

# Menentukan label prediksi

In [167]:
y = hr_df['salary']
y

0           low
1        medium
2        medium
3           low
4           low
          ...  
14994       low
14995       low
14996       low
14997       low
14998       low
Name: salary, Length: 14999, dtype: object

# Menentukan prediktor

In [168]:
prediktor = ['satisfaction_level', 'number_project', 'time_spend_company', 'average_montly_hours']
X = hr_df[prediktor]
X

satisfaction_level  number_project  time_spend_company  \
0                    0.38               2                   3   
1                    0.80               5                   6   
2                    0.11               7                   4   
3                    0.72               5                   5   
4                    0.37               2                   3   
...                   ...             ...                 ...   
14994                0.40               2                   3   
14995                0.37               2                   3   
14996                0.37               2                   3   
14997                0.11               6                   4   
14998                0.37               2                   3   

       average_montly_hours  
0                       157  
1                       262  
2                       272  
3                       223  
4                       159  
...                     ...  
14994                   151  
14995                   160  
14996                   143  
14997                   280  
14998                   158  

[14999 rows x 4 columns]

In [169]:
X.describe()

satisfaction_level  number_project  time_spend_company  \
count        14999.000000    14999.000000        14999.000000   
mean             0.612834        3.803054            3.498233   
std              0.248631        1.232592            1.460136   
min              0.090000        2.000000            2.000000   
25%              0.440000        3.000000            3.000000   
50%              0.640000        4.000000            3.000000   
75%              0.820000        5.000000            4.000000   
max              1.000000        7.000000           10.000000   

       average_montly_hours  
count          14999.000000  
mean             201.050337  
std               49.943099  
min               96.000000  
25%              156.000000  
50%              200.000000  
75%              245.000000  
max              310.000000

# Membagi dataset menjadi training dan testing set

In [171]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 10)


# Machine learning

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# K nearest neighbors

In [172]:
from sklearn.neighbors import KNeighborsClassifier

In [173]:
k_range = list(range(1,26))
nilai = []
for k in k_range:
    model_knn = KNeighborsClassifier(n_neighbors = k)
    model_knn.fit(X_train, y_train)
    y_pred = model_knn.predict(X_test)
    nilai.append(accuracy_score(y_test, y_pred))

In [174]:
model_knn = KNeighborsClassifier(n_neighbors = 3)
model_knn.fit(X_train, y_train)
y_pred = model_knn.predict(X_test)

## Accuracy

In [175]:
print(accuracy_score(y_test, y_pred))

0.4965


## Confusion matrix

In [176]:
print(confusion_matrix(y_test, y_pred))

[[ 112  186  178]
 [ 272 1652 1004]
 [ 290 1091 1215]]


## Classification report

In [177]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

        high       0.17      0.24      0.19       476
         low       0.56      0.56      0.56      2928
      medium       0.51      0.47      0.49      2596

    accuracy                           0.50      6000
   macro avg       0.41      0.42      0.42      6000
weighted avg       0.51      0.50      0.50      6000



# Logistic regression

In [178]:
from sklearn.linear_model import LogisticRegression

In [184]:
model_logreg = LogisticRegression(solver = 'lbfgs', multi_class = 'auto')
model_logreg.fit(X_train, y_train)
y_pred = model_logreg.predict(X_test)

/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


## Accuracy

In [180]:
print(accuracy_score(y_test, y_pred))

0.4825


## Confusion matrix

In [181]:
print(confusion_matrix(y_test, y_pred))

[[   0  366  110]
 [   0 2296  632]
 [   0 1997  599]]


## Classification report

In [182]:
print(classification_report(y_test, y_pred))

/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

        high       0.00      0.00      0.00       476
         low       0.49      0.78      0.61      2928
      medium       0.45      0.23      0.30      2596

    accuracy                           0.48      6000
   macro avg       0.31      0.34      0.30      6000
weighted avg       0.43      0.48      0.43      6000



# Support vendor classifier

In [185]:
from sklearn.svm import SVC

In [186]:
model_svc = SVC(gamma = 'scale')
model_svc.fit(X_train, y_train)
y_pred = model_svc.predict(X_test)

## Accuracy

In [187]:
print(accuracy_score(y_test, y_pred))

0.488


## Confusion matrix

In [188]:
print(confusion_matrix(y_test, y_pred))

[[   0  476    0]
 [   0 2928    0]
 [   0 2596    0]]


## Classification report

In [189]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

        high       0.00      0.00      0.00       476
         low       0.49      1.00      0.66      2928
      medium       0.00      0.00      0.00      2596

    accuracy                           0.49      6000
   macro avg       0.16      0.33      0.22      6000
weighted avg       0.24      0.49      0.32      6000



/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Decision Tree Classifier

In [190]:
from sklearn.tree import DecisionTreeClassifier

In [191]:
model_dt = DecisionTreeClassifier()
model_dt.fit(X_train, y_train)
y_pred = model_dt.predict(X_test)

## Accuracy

In [192]:
print(accuracy_score(y_test, y_pred))

0.5455


## Confusion matrix

In [193]:
print(confusion_matrix(y_test, y_pred))

[[ 154  165  157]
 [ 203 1782  943]
 [ 229 1030 1337]]


## Classification report

In [194]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

        high       0.26      0.32      0.29       476
         low       0.60      0.61      0.60      2928
      medium       0.55      0.52      0.53      2596

    accuracy                           0.55      6000
   macro avg       0.47      0.48      0.47      6000
weighted avg       0.55      0.55      0.55      6000



# Random Forest Classifier

In [195]:
from sklearn.ensemble import RandomForestClassifier

In [196]:
model_dt = DecisionTreeClassifier()
model_dt.fit(X_train, y_train)
y_pred = model_dt.predict(X_test)

## Accuracy

In [197]:
print(accuracy_score(y_test, y_pred))

0.546


## Confusion matrix

In [198]:
print(confusion_matrix(y_test, y_pred))

[[ 155  156  165]
 [ 204 1780  944]
 [ 213 1042 1341]]


## Classification report

In [199]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

        high       0.27      0.33      0.30       476
         low       0.60      0.61      0.60      2928
      medium       0.55      0.52      0.53      2596

    accuracy                           0.55      6000
   macro avg       0.47      0.48      0.48      6000
weighted avg       0.55      0.55      0.55      6000

